# Proyecto FIFA World Cup 2022
## Fase 1: Definición del problema y entorno reproducible

**Asignatura:** MCDI500 – Herramientas de Software Científico

**Integrantes:**
- Enzo Pinilla
- Claudio Alarcón
- Luis Espinoza

**Docente:** Dr. Omar Salinas Silva

**Objetivo de la Fase 1:** establecer la base técnica y metodológica del proyecto mediante la definición del problema, la configuración del entorno reproducible y la validación inicial del conjunto de datos.

# Problemática

La Copa Mundial FIFA Qatar 2022 generó una gran cantidad de información estadística relacionada con el desempeño de las selecciones participantes. Sin embargo, la existencia de múltiples indicadores deportivos dificulta determinar cuáles de estas variables presentan una mayor influencia sobre la obtención de victorias durante el torneo.

Variables como la posesión de balón, la cantidad de pases, los intentos al arco, las faltas o las tarjetas disciplinarias podrían influir en el resultado de un partido, pero su impacto no resulta evidente sin un análisis sistemático de los datos.

Para abordar esta problemática es necesario disponer de un entorno de trabajo reproducible que permita organizar adecuadamente los datos, documentar las decisiones metodológicas, registrar los cambios realizados y garantizar que los resultados puedan ser replicados y verificados por cualquier integrante del equipo.

# Pregunta orientadora

¿Qué estadísticas de juego influyen en la victoria de una selección durante la Copa Mundial FIFA Qatar 2022?

# Objetivo general

Desarrollar un entorno reproducible para analizar las estadísticas de juego del Mundial FIFA Qatar 2022 e identificar variables asociadas a la victoria de una selección mediante herramientas de ciencia de datos, documentación técnica y control de versiones colaborativo.

# Objetivos específicos

1. Organizar una estructura de repositorio que permita separar datos originales, datos procesados, notebooks, documentación, resultados y código reutilizable.

2. Configurar un entorno reproducible mediante Python, Jupyter Notebook y un archivo requirements.txt.

3. Explorar y documentar las características principales del dataset FIFA World Cup 2022.

4. Implementar control de versiones mediante Git y GitHub utilizando ramas y commits descriptivos.

5. Vincular la documentación técnica, los notebooks y el repositorio con el flujo de trabajo definido para el proyecto.

# Dataset utilizado

Para el desarrollo del proyecto se utilizará el conjunto de datos:

**FIFA World Cup 2022 Complete Dataset**

Fuente: https://www.kaggle.com/datasets/die9origephit/fifa-world-cup-2022-complete-dataset

El dataset contiene información detallada de los partidos disputados durante la Copa Mundial FIFA Qatar 2022.

Entre las variables disponibles se encuentran:

- Goles
- Asistencias
- Posesión de balón
- Pases completados
- Intentos al arco
- Tarjetas amarillas
- Tarjetas rojas
- Faltas
- Offsides
- Resultado final

Estas variables permiten realizar análisis descriptivos para identificar posibles relaciones entre el rendimiento estadístico de una selección y la obtención de victorias.

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# Función de carga de datos

Para favorecer la reutilización del código y mantener una estructura reproducible, la lectura del dataset se implementa mediante una función.

In [2]:
def cargar_datos(ruta):
    """
    Carga el dataset FIFA World Cup 2022 desde la ruta especificada.

    Parameters
    ----------
    ruta : str
        Ruta del archivo CSV.

    Returns
    -------
    pandas.DataFrame
        DataFrame con los datos cargados.
    """
    ruta = Path(ruta)
    rutas_posibles = [
        ruta,
        Path.cwd() / ruta,
        Path.cwd().parent / ruta,
        Path.cwd() / "data" / "raw" / "Fifa_world_cup_matches.csv",
        Path.cwd().parent / "data" / "raw" / "Fifa_world_cup_matches.csv",
    ]

    for ruta_posible in rutas_posibles:
        if ruta_posible.exists():
            return pd.read_csv(ruta_posible)

    raise FileNotFoundError(
        "No se encontro el CSV. Usa data/raw/Fifa_world_cup_matches.csv "
        "o verifica el directorio desde donde se ejecuta el notebook."
    )

# Carga inicial del dataset

La siguiente celda realiza la lectura del archivo CSV almacenado en la carpeta data/raw.

In [3]:
df = cargar_datos("../data/raw/Fifa_world_cup_matches.csv")

# Validación de estructura

A continuación se verifica la cantidad de registros y variables disponibles en el dataset.

In [4]:
print("Dimensiones del dataset:")
print(df.shape)

Dimensiones del dataset:
(64, 88)

# Vista preliminar de los datos

Se muestran las primeras filas para comprender la estructura del conjunto de datos y validar que la carga fue exitosa.

In [5]:
df.head()

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
0,QATAR,ECUADOR,42%,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,...,0,1,6,5,0,0,52,72,256,279
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,...,0,1,8,13,0,0,63,72,139,416
2,SENEGAL,NETHERLANDS,44%,45%,11%,0,2,21 NOV 2022,17 : 00,Group A,...,0,0,9,15,0,0,63,73,263,251
3,UNITED STATES,WALES,51%,39%,10%,1,1,21 NOV 2022,20 : 00,Group B,...,0,1,7,7,0,0,81,72,242,292
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%,1,2,22 NOV 2022,11 : 00,Group C,...,1,0,4,14,0,0,65,80,163,361

# Información general del dataset

La siguiente celda permite inspeccionar tipos de datos y posibles valores faltantes.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 88 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   team1                                                  64 non-null     object
 1   team2                                                  64 non-null     object
 2   possession team1                                       64 non-null     object
 3   possession team2                                       64 non-null     object
 4   possession in contest                                  64 non-null     object
 5   number of goals team1                                  64 non-null     int64
 6   number of goals team2                                  64 non-null     int64
 7   date                                                   64 non-null     object
 8   hour                                                   64 non-null     object
 9   category                                               64 non-null     object
 10  total attempts team1                                   64 non-null     int64
 11  total attempts team2                                   64 non-null     int64
 12  conceded team1                                         64 non-null     int64
 13  conceded team2                                         64 non-null     int64
 14  goal inside the penalty area team1                     64 non-null     int64
 15  goal inside the penalty area team2                     64 non-null     int64
 16  goal outside the penalty area team1                    64 non-null     int64
 17  goal outside the penalty area team2                    64 non-null     int64
 18  assists team1                                          64 non-null     int64
 19  assists team2                                          64 non-null     int64
 20  on target attempts team1                               64 non-null     int64
 21  on target attempts team2                               64 non-null     int64
 22  off target attempts team1                              64 non-null     int64
 23  off target attempts team2                              64 non-null     int64
 24  attempts inside the penalty area team1                 64 non-null     int64
 25  attempts inside the penalty area  team2                64 non-null     int64
 26  attempts outside the penalty area  team1               64 non-null     int64
 27  attempts outside the penalty area  team2               64 non-null     int64
 28  left channel team1                                     64 non-null     int64
 29  left channel team2                                     64 non-null     int64
 30  left inside channel team1                              64 non-null     int64
 31  left inside channel team2                              64 non-null     int64
 32  central channel team1                                  64 non-null     int64
 33  central channel team2                                  64 non-null     int64
 34  right inside channel team1                             64 non-null     int64
 35  right inside channel team2                             64 non-null     int64
 36  right channel team1                                    64 non-null     int64
 37  right channel team2                                    64 non-null     int64
 38  total offers to receive team1                          64 non-null     int64
 39  total offers to receive team2                          64 non-null     int64
 40  inbehind offers to receive team1                       64 non-null     int64
 41  inbehind offers to receive team2                       64 non-null     int64
 42  inbetween offers to receive team1                      64 non-null     int64
 43  inbetween offers to receive team2                      64 non-null     int64
 44  infront offers to receive team1                        64 non-null     int64
 45  infront offers to receive team2                        64 non-null     int64
 46  receptions between midfield and defensive lines team1  64 non-null     int64
 47  receptions between midfield and defensive lines team2  64 non-null     int64
 48  attempted line breaks team1                            64 non-null     int64
 49  attempted line breaks team2                            64 non-null     int64
 50  completed line breaksteam1                             64 non-null     int64
 51  completed line breaks team2                            64 non-null     int64
 52  attempted defensive line breaks team1                  64 non-null     int64
 53  attempted defensive line breaks team2                  64 non-null     int64
 54  completed defensive line breaksteam1                   64 non-null     int64
 55  completed defensive line breaks team2                  64 non-null     int64
 56  yellow cards team1                                     64 non-null     int64
 57  yellow cards team2                                     64 non-null     int64
 58  red cards team1                                        64 non-null     int64
 59  red cards team2                                        64 non-null     int64
 60  fouls against team1                                    64 non-null     int64
 61  fouls against team2                                    64 non-null     int64
 62  offsides team1                                         64 non-null     int64
 63  offsides team2                                         64 non-null     int64
 64  passes team1                                           64 non-null     int64
 65  passes team2                                           64 non-null     int64
 66  passes completed team1                                 64 non-null     int64
 67  passes completed team2                                 64 non-null     int64
 68  crosses team1                                          64 non-null     int64
 69  crosses team2                                          64 non-null     int64
 70  crosses completed team1                                64 non-null     int64
 71  crosses completed team2                                64 non-null     int64
 72  switches of play completed team1                       64 non-null     int64
 73  switches of play completed team2                       64 non-null     int64
 74  corners team1                                          64 non-null     int64
 75  corners team2                                          64 non-null     int64
 76  free kicks team1                                       64 non-null     int64
 77  free kicks team2                                       64 non-null     int64
 78  penalties scored team1                                 64 non-null     int64
 79  penalties scored team2                                 64 non-null     int64
 80  goal preventions team1                                 64 non-null     int64
 81  goal preventions team2                                 64 non-null     int64
 82  own goals team1                                        64 non-null     int64
 83  own goals team2                                        64 non-null     int64
 84  forced turnovers team1                                 64 non-null     int64
 85  forced turnovers team2                                 64 non-null     int64
 86  defensive pressures applied team1                      64 non-null     int64
 87  defensive pressures applied team2                      64 non-null     int64
dtypes: int64(80), object(8)
memory usage: 44.1+ KB

# Estadísticas descriptivas iniciales

Se generan métricas descriptivas básicas para obtener una primera comprensión del contenido del dataset.

In [7]:
df.describe()

,number of goals team1,number of goals team2,total attempts team1,total attempts team2,conceded team1,conceded team2,goal inside the penalty area team1,goal inside the penalty area team2,goal outside the penalty area team1,goal outside the penalty area team2,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
count,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,...,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000
mean,1.578125,1.109375,11.140625,11.281250,1.109375,1.578125,1.468750,0.984375,0.093750,0.109375,...,0.140625,0.125000,11.593750,11.359375,0.015625,0.015625,71.968750,70.125000,289.750000,293.265625
std,1.551289,1.055856,4.972519,5.807682,1.055856,1.551289,1.563155,0.999876,0.293785,0.314576,...,0.350382,0.377964,5.911299,4.990045,0.125000,0.125000,14.394629,13.531269,88.406888,80.916230
min,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,38.000000,44.000000,139.000000,141.000000
25%,0.000000,0.000000,8.000000,7.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,7.750000,8.000000,0.000000,0.000000,63.000000,60.250000,229.000000,233.750000
50%,1.000000,1.000000,10.000000,10.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,11.000000,10.000000,0.000000,0.000000,71.000000,72.000000,281.000000,292.500000
75%,2.000000,2.000000,14.000000,14.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,14.000000,14.000000,0.000000,0.000000,83.500000,79.000000,328.000000,327.500000
max,7.000000,4.000000,25.000000,32.000000,4.000000,7.000000,7.000000,4.000000,1.000000,1.000000,...,1.000000,2.000000,32.000000,26.000000,1.000000,1.000000,101.000000,104.000000,637.000000,585.000000

# Interpretación inicial

La carga del dataset fue realizada correctamente y se verificó la disponibilidad de las variables necesarias para el análisis.

La inspección inicial permite conocer la cantidad de registros, la estructura de las columnas y los tipos de datos presentes en el conjunto de información.

Esta revisión preliminar constituye el punto de partida para las actividades de exploración y limpieza que serán desarrolladas en las siguientes fases del proyecto.

# Conclusiones de la Fase 1

Durante esta primera fase se definió la problemática del proyecto, se establecieron los objetivos generales y específicos, se configuró la estructura inicial del repositorio y se validó la carga del dataset FIFA World Cup 2022.

Asimismo, se verificó el correcto funcionamiento del entorno reproducible basado en Python, Jupyter Notebook y GitHub, permitiendo garantizar que los análisis posteriores puedan ejecutarse de forma consistente y trazable.

Las siguientes etapas del proyecto estarán orientadas a la exploración de datos, la limpieza y transformación del dataset, el análisis descriptivo de las variables y la identificación de patrones asociados a la victoria de las selecciones participantes.